### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/JUMS-Project#1]
Bug Description: "user not found!" popup showing in correctly

Bug screenshot: 

![image](https://github.com/M8Fayaz/JUMS-Project/assets/120467524/f26c0983-d0e7-4c99-a2a2-a3cacc060ce7)

**Comment by M8Fayaz** [comment]
need to change the spelling of the **user**

**Comment by rajkumarkm8** [comment]
error message "user not found" issue fixed in the live server
