### ISSUE TITLE
Packages / PV

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/JUMS-Project#26]
Bug Description: Deleted or edited Packages should not listed in Pv list.

Bug screen shot: 
![image](https://github.com/M8Fayaz/JUMS-Project/assets/120467524/25bf1fc5-ea36-410d-9fe6-3ba29673792f)
![image](https://github.com/M8Fayaz/JUMS-Project/assets/120467524/0f63cba7-16c8-4409-ae5b-6e80c3303c77)

**Comment by ReMiGioUs037** [comment]
@rajkumarkm8 pls check

**Comment by m8dharma** [comment]
It working pls check again
