### ISSUE TITLE
Home page / Profile icon / My profile

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/JUMS-Project#3]
Bug Description: the system upload any type of files in the profile field

Bug Screenshot:

![image](https://github.com/M8Fayaz/JUMS-Project/assets/120467524/246d0c18-45ba-4931-9d32-6e95b22de1bc)

**Comment by M8Fayaz** [comment]
the system should allow the user to upload image files only

**Comment by ReMiGioUs037** [comment]
Fixed pls check @M8Fayaz

**Comment by M8Fayaz** [comment]
fixed
