### ISSUE TITLE
Home page / Profil logo / Settings / Google key

### ISSUE THREAD

**Issue by M8Fayaz** [FayazM8/JUMS-Project#4]
Bug Description: Google Key field should not save empty space.

Bug Screenshot: 

![image](https://github.com/M8Fayaz/JUMS-Project/assets/120467524/c8ac40c8-8386-4a9e-abbf-c871f52a1699)

**Comment by ReMiGioUs037** [comment]
Fixed pls check @M8Fayaz

**Comment by M8Fayaz** [comment]
pass
